server.port=${PORT:8080}
spring.application.name=news-portal
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
firebase.project-id=${FIREBASE_PROJECT_ID:local-news-portal}
firebase.client-email=${FIREBASE_CLIENT_EMAIL:local-emulator@example.com}
firebase.private-key=${FIREBASE_PRIVATE_KEY:local-dev-private-key}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/news_portal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:news_portal}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:news_portal}
